#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------
# What kind of thing is this ("workshop")? #Don't Change
kind: "workshop"
# Is this a permanent page 'static' or a taught workshop 'dated'
delivery: "dated"

# Overall title for the Workshop.
# This variable is used to (optionally) add a title in the "jumbotron"
# (the grey box at the top of the page), and to the extra pages.
title: "Computational Research Skills"
form_title: "Computational+Research+Skills" # This is required for the surveys

# Email address, no mailto:
email: "rsginfo@soton.ac.uk"
logo_site: "https://rsgsoton.net"

# For static delivery this section can all be ignored ==================================================================
# Specify the location of the workshop
venue: "online"           # name of location use "online" if online
address: "TBC"         # address of location or url of platform
platform-name: "Teams"   # name of online platform e.g. Teams, Zoom e.t.c
country: "gb"         # e.g. gb
language: "en"        # e.g. en
latitude: "50.909698"    # latitude of location (Soton: 50.909698)
longitude: "-1.404351"   # longitude of location (Soton: -1.404351)

# Specify the start and end date of the workshop
humandate: "3rd July - 12th July 2023"      # e.g. "6th August"
humantime: "09:30-13:00"      # e.g. "09:00-17:00"
startdate: 2023-07-03        # e.g. YYYY-MM-DD # This is required for the surveys NOTE: 1990-1-1 will not work
enddate: 2023-07-12         # e.g. YYYY-MM-DD

# Specify the details of the instructors and helpers
# Can be list, or single string
instructor:
  - "Philippa Broadbent"
  - "Sam Mangham"
  - "Ed Parkinson"
  - "Steve Crouch"
instructor-email:
  - "p.k.broadbent@soton.ac.uk"
  - "s.mangham@soton.ac.uk"
  - "e.parkinson@soton.ac.uk"
  - "stc@ecs.soton.ac.uk"
helper:
  - "Mehtap Özbey Arabaci"
  - "Hugh Warden"
# ======================================================================================================================

# Details about the lessons
lessons:
#   - title: Best Practices in Data Organisation Using Spreadsheets
#     gh-name: spreadsheets
#     type: episode
#     branch: main
#     date: 6 March 2023
#     start-time: 09:30
#     order: 1

#   - title: Data Cleaning with OpenRefine
#     gh-name: openrefine-data-cleaning
#     type: episode
#     branch: main
#     date: 7 March 2023
#     start-time: 09:30
#     order: 2

  - title: Automating Tasks with the Unix Shell  # Lesson title
    org-name: Southampton-RSG-Training           # Name of the GitHub organisation (or individual) the lesson is in defaults to Southampton-RSG-Training
    gh-name: shell-novice                        # Name of the GitHub repository for the lesson at https://github:com/{org-name}:
    type: episode                                # Currently only 'episode' or 'episode_r' is valid
    branch: main                                 # Set the branch of the repository to use, useful for lesson customization
    date: 3 July 2023                         # The date of the lesson                   # date and start-time are required for z
    start-time: 09:30                            # The start time of the lesson             # 'kind: workshop'
    order: 3                                     # The position of the lesson in the course # order is required for 'delivery: static'

  - title: Version Control with git
    gh-name: git-novice
    type: episode
    branch: main
    date: 4 July 2023
    start-time: 09:30
    order: 4
    
#   - title: Managing Academic Software Development
#     gh-name: project-novice
#     type: episode
#     branch: main
#     date: 15 March 2023
#     start-time: 09:30
#     order: 5

  - title: Building Programs with Python
    gh-name: python-novice
    type: episode
    branch: main
    date:
      - 5 July 2023
      - 6 July 2023
    start-time:
      - 09:30
      - 09:30
    order: 6

  - title: Data Analysis and Visualization in R
    gh-name: r-novice
    type: episode
    branch: main
    date:
      - 10 July 2023
      - 11 July 2023
      - 12 July 2023
    start-time:
      - 09:30
      - 09:30
      - 09:30
    order: 7

###
# It is unlikely you need to modify the values below this line
###

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:slug

include:
  - _includes/rsg/

# If there is both an R and python official version of a curriculum
# (as listed on https://software-carpentry.org/lessons/ and
# https://datacarpentry.org/lessons/), change the
# value of the variable below ("flavor") to get the schedule and installation
# instructions updated accordingly (valid values are 'r' or 'python').
# Note: this is only for Data Carpentry and SWC at this time.
flavor: "python"

# If the workshop will be a lesson pilot (for a new official lesson or
# a lesson in The Carpentries Incubator), set pilot to "true".
pilot: false

# rsg: Custom Lessons from the Southampton-RSG-Training git-org
carpentry: "rsg"

# Sites.
amy_site: "https://amy.carpentries.org/"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
incubator: "https://github.com/carpentries-incubator/"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page


# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - .vendor/
  - vendor/
  - .docker-vendor/
  - submodules/

# Turn on built-in syntax highlighting.
highlighter: rouge

# Using the new jekyll remote themes
remote_theme: Southampton-RSG-Training/rsg-theme

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-github-metadata
